### ISSUE TITLE
Test errors version 0.3.2

### ISSUE THREAD

**Issue by ehoeve** [TOETOE55/lens-rs#4]
I get the following test errors when i try to do cargo test:

failures:
    src/lib.rs - (line 103)
    src/lib.rs - (line 115)
    src/lib.rs - (line 131)
    src/lib.rs - (line 182)
    src/lib.rs - (line 222)
    src/lib.rs - (line 35)
    src/lib.rs - (line 45)
    src/lib.rs - (line 54)
    src/lib.rs - (line 63)
    src/lib.rs - (line 72)
    src/lib.rs - (line 87)
    src/lib.rs - Optics (line 222)
    src/lib.rs - optics (line 222)
    src/traits.rs - traits::prism (line 56)
    src/traits.rs - traits::traversal (line 24)

**Comment by TOETOE55** [comment]
Hello, the `cargo test` would run the code in the comments, but it's not the test. You should run the test on `lens-rs_test`.

**Comment by ruifengx** [comment]
AFAIK, doc tests are widely used in the Rust community. Would you consider converting the code fragments to doc tests (so that they _are_ tested) or just mark them as `ignore` (so that they are completely ignored in `cargo test`) or `no_run` (so that they are only compiled but not run during `cargo test`)? I can submit a PR for the changes if you are willing to accept it (though it might take a while).

So as an example, for the code fragment here:
https://github.com/TOETOE55/lens-rs/blob/53be002004bbed192cbc2ec79ee31f8eabee9f35/lens-rs/src/lib.rs#L35-L41

You can either add enough context for actually compiling and running it as a test (and optionally precede these added lines with a `#` so that they are hidden in generated docs) (also note that the `rust` in the code fences are optional, because code fragments are by default in Rust; I personally prefer them omitted):
```rust
//! ```
//! # use lens_rs::optics;
//! # struct Foo { a: String, b: i32 }
//! let mut x = Foo { a: String::from(".a in Foo"), b: 0 };
//! assert_eq!(x.view_ref(optics!(a)), ".a in Foo");
//!
//! *x.view_mut(optics!(b)) += 1;
//! assert_eq!(x.view_ref(optics!(b)), &1)
//! ```
```

Or we can simply mark the code as `ignore`:
```rust
//! ```ignore
//! let mut x = Foo { a: String::from(".a in Foo"), b: 0 };
//! assert_eq!(x.view_ref(optics!(a)), ".a in Foo");
//!
//! *x.view_mut(optics!(b)) += 1;
//! assert_eq!(x.view_ref(optics!(b)), &1)
//! ```
```

For details, please refer to [`rustdoc` documentations](https://doc.rust-lang.org/rustdoc/documentation-tests.html).

**Comment by TOETOE55** [comment]
OK, fixed it~thanks.
